	CREATE TABLE IT490.Users(
        User_ID INT NOT NULL AUTO_INCREMENT,
        F_Name VARCHAR(30) NOT NULL,
        L_Name VARCHAR(30) NOT NULL,
        Email VARCHAR(255) NOT NULL,
        Password VARCHAR(80) NOT NULL,
        created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (User_ID),
        UNIQUE (Email)
